// TODO: autogenerate me!

#include <Wt/Auth/AbstractPasswordService>
#include <Wt/Auth/AbstractUserDatabase>
#include <Wt/Auth/AuthModel>
#include <Wt/Auth/AuthService>
#include <Wt/Auth/AuthWidget>
#include <Wt/Auth/Dbo/AuthInfo>
#include <Wt/Auth/Dbo/UserDatabase>
#include <Wt/Auth/FacebookService>
#include <Wt/Auth/FormBaseModel>
#include <Wt/Auth/GoogleService>
#include <Wt/Auth/HashFunction>
#include <Wt/Auth/Identity>
#include <Wt/Auth/Login>
#include <Wt/Auth/LostPasswordWidget>
#include <Wt/Auth/OAuthService>
#include <Wt/Auth/PasswordHash>
#include <Wt/Auth/PasswordPromptDialog>
#include <Wt/Auth/PasswordService>
#include <Wt/Auth/PasswordStrengthValidator>
#include <Wt/Auth/PasswordVerifier>
#include <Wt/Auth/RegistrationModel>
#include <Wt/Auth/RegistrationWidget>
#include <Wt/Auth/Token>
#include <Wt/Auth/UpdatePasswordWidget>
#include <Wt/Auth/User>
#include <Wt/Chart/WAbstractChart>
#include <Wt/Chart/WAxis>
#include <Wt/Chart/WCartesianChart>
#include <Wt/Chart/WChart2DRenderer>
#include <Wt/Chart/WChartGlobal>
#include <Wt/Chart/WChartPalette>
#include <Wt/Chart/WDataSeries>
#include <Wt/Chart/WPieChart>
#include <Wt/Chart/WStandardPalette>
#include <Wt/Dbo/backend/Postgres>
#include <Wt/Dbo/backend/Sqlite3>
#include <Wt/Dbo/backend/WDboPostgresDllDefs.h>
#include <Wt/Dbo/backend/WDboSqlite3DllDefs.h>
#include <Wt/Dbo/Call>
#include <Wt/Dbo/Call_impl.h>
#include <Wt/Dbo/collection>
#include <Wt/Dbo/collection_impl.h>
#include <Wt/Dbo/DbAction>
#include <Wt/Dbo/DbAction_impl.h>
#include <Wt/Dbo/Dbo>
#include <Wt/Dbo/Exception>
#include <Wt/Dbo/Field>
#include <Wt/Dbo/Field_impl.h>
#include <Wt/Dbo/FixedSqlConnectionPool>
#include <Wt/Dbo/Impl>
#include <Wt/Dbo/ptr>
#include <Wt/Dbo/ptr_impl.h>
#include <Wt/Dbo/ptr_tuple>
#include <Wt/Dbo/Query>
#include <Wt/Dbo/Query_impl.h>
#include <Wt/Dbo/QueryColumn>
#include <Wt/Dbo/QueryModel>
#include <Wt/Dbo/QueryModel_impl.h>
#include <Wt/Dbo/Session>
#include <Wt/Dbo/Session_impl.h>
#include <Wt/Dbo/SqlConnection>
#include <Wt/Dbo/SqlConnectionPool>
#include <Wt/Dbo/SqlStatement>
#include <Wt/Dbo/SqlTraits>
#include <Wt/Dbo/SqlTraits_impl.h>
#include <Wt/Dbo/StdSqlTraits>
#include <Wt/Dbo/Transaction>
#include <Wt/Dbo/Types>
#include <Wt/Dbo/WDboDllDefs.h>
#include <Wt/Dbo/weak_ptr>
#include <Wt/Dbo/weak_ptr_impl.h>
#include <Wt/Dbo/WtSqlTraits>
#include <Wt/Http/Client>
#include <Wt/Http/Message>
#include <Wt/Http/Method>
#include <Wt/Http/Request>
#include <Wt/Http/Response>
#include <Wt/Http/ResponseContinuation>
#include <Wt/Http/WtClient>
#include <Wt/Json/Array>
#include <Wt/Json/Object>
#include <Wt/Json/Parser>
#include <Wt/Json/Value>
#include <Wt/Mail/Client>
#include <Wt/Mail/Mailbox>
#include <Wt/Mail/Message>
#include <Wt/Payment/Address>
#include <Wt/Payment/Customer>
#include <Wt/Payment/Money>
#include <Wt/Payment/Order>
#include <Wt/Payment/OrderItem>
#include <Wt/Payment/PayPal>
#include <Wt/Payment/Result>
#include <Wt/Render/WPdfRenderer>
#include <Wt/Render/WTextRenderer>
#include <Wt/SyncLock>
#include <Wt/Test/WTestEnvironment>
#include <Wt/Utils>
#include <Wt/WAbstractArea>
#include <Wt/WAbstractItemDelegate>
#include <Wt/WAbstractItemModel>
#include <Wt/WAbstractItemView>
#include <Wt/WAbstractListModel>
#include <Wt/WAbstractMedia>
#include <Wt/WAbstractProxyModel>
#include <Wt/WAbstractSpinBox>
#include <Wt/WAbstractTableModel>
#include <Wt/WAbstractToggleButton>
#include <Wt/WAccordionLayout>
#include <Wt/WAggregateProxyModel>
#include <Wt/WAnchor>
#include <Wt/WAnimation>
#include <Wt/WApplication>
#include <Wt/WAudio>
#include <Wt/WBatchEditProxyModel>
#include <Wt/WBoostAny>
#include <Wt/WBorder>
#include <Wt/WBorderLayout>
#include <Wt/WBoxLayout>
#include <Wt/WBreak>
#include <Wt/WBrush>
#include <Wt/WButtonGroup>
#include <Wt/WCalendar>
#include <Wt/WCanvasPaintDevice>
#include <Wt/WCheckBox>
#include <Wt/WCircleArea>
#include <Wt/WColor>
#include <Wt/WCombinedLocalizedStrings>
#include <Wt/WComboBox>
#include <Wt/WCompositeWidget>
#include <Wt/WConfig.h>
#include <Wt/WContainerWidget>
#include <Wt/WCssDecorationStyle>
#include <Wt/WCssStyleSheet>
#include <Wt/WDate>
#include <Wt/WDatePicker>
#include <Wt/WDateTime>
#include <Wt/WDateValidator>
#include <Wt/WDefaultLayout>
#include <Wt/WDefaultLoadingIndicator>
#include <Wt/WDialog>
#include <Wt/WDllDefs.h>
#include <Wt/WDoubleSpinBox>
#include <Wt/WDoubleValidator>
#include <Wt/WEnvironment>
#include <Wt/WEvent>
#include <Wt/WException>
#include <Wt/WFileResource>
#include <Wt/WFileUpload>
#include <Wt/WFitLayout>
#include <Wt/WFlags>
#include <Wt/WFlashObject>
#include <Wt/WFont>
#include <Wt/WFontMetrics>
#include <Wt/WFormModel>
#include <Wt/WFormWidget>
#include <Wt/WGenericMatrix>
#include <Wt/WGlobal>
#include <Wt/WGLWidget>
#include <Wt/WGoogleMap>
#include <Wt/WGridLayout>
#include <Wt/WGroupBox>
#include <Wt/WHBoxLayout>
#include <Wt/WHTML5Audio>
#include <Wt/WHTML5Video>
#include <Wt/WIconPair>
#include <Wt/WImage>
#include <Wt/WInPlaceEdit>
#include <Wt/WInteractWidget>
#include <Wt/WIntValidator>
#include <Wt/WIOService>
#include <Wt/WItemDelegate>
#include <Wt/WItemSelectionModel>
#include <Wt/WJavaScript>
#include <Wt/WJavaScriptPreamble>
#include <Wt/WJavaScriptSlot>
#include <Wt/WLabel>
#include <Wt/WLayout>
#include <Wt/WLayoutItem>
#include <Wt/WLayoutItemImpl>
#include <Wt/WLength>
#include <Wt/WLengthValidator>
#include <Wt/WLineEdit>
#include <Wt/WLineF>
#include <Wt/WLink>
#include <Wt/WLoadingIndicator>
#include <Wt/WLocalizedStrings>
#include <Wt/WLogger>
#include <Wt/WMatrix4x4>
#include <Wt/WMediaPlayer>
#include <Wt/WMemoryResource>
#include <Wt/WMenu>
#include <Wt/WMenuItem>
#include <Wt/WMessageBox>
#include <Wt/WMessageResourceBundle>
#include <Wt/WMessageResources>
#include <Wt/WModelIndex>
#include <Wt/WObject>
#include <Wt/WOverlayLoadingIndicator>
#include <Wt/WPaintDevice>
#include <Wt/WPaintedWidget>
#include <Wt/WPainter>
#include <Wt/WPainterPath>
#include <Wt/WPanel>
#include <Wt/WPdfImage>
#include <Wt/WPen>
#include <Wt/WPoint>
#include <Wt/WPointF>
#include <Wt/WPolygonArea>
#include <Wt/WPopupMenu>
#include <Wt/WPopupMenuItem>
#include <Wt/WProgressBar>
#include <Wt/WPushButton>
#include <Wt/WRadioButton>
#include <Wt/WRandom>
#include <Wt/WRasterImage>
#include <Wt/WReadOnlyProxyModel>
#include <Wt/WRectArea>
#include <Wt/WRectF>
#include <Wt/WRegExp>
#include <Wt/WRegExpValidator>
#include <Wt/WResource>
#include <Wt/WScrollArea>
#include <Wt/WScrollBar>
#include <Wt/WSelectionBox>
#include <Wt/WServer>
#include <Wt/WShadow>
#include <Wt/WSignal>
#include <Wt/WSignalMapper>
#include <Wt/WSlider>
#include <Wt/WSocketNotifier>
#include <Wt/WSortFilterProxyModel>
#include <Wt/WSound>
#include <Wt/WSpinBox>
#include <Wt/WSslCertificate>
#include <Wt/WSslInfo>
#include <Wt/WStackedWidget>
#include <Wt/WStandardItem>
#include <Wt/WStandardItemModel>
#include <Wt/WStatelessSlot>
#include <Wt/WStreamResource>
#include <Wt/WString>
#include <Wt/WStringListModel>
#include <Wt/WStringStream>
#include <Wt/WStringUtil>
#include <Wt/WSubMenuItem>
#include <Wt/WSuggestionPopup>
#include <Wt/WSvgImage>
#include <Wt/WTable>
#include <Wt/WTableCell>
#include <Wt/WTableColumn>
#include <Wt/WTableRow>
#include <Wt/WTableView>
#include <Wt/WTabWidget>
#include <Wt/WTemplate>
#include <Wt/WTemplateFormView>
#include <Wt/WText>
#include <Wt/WTextArea>
#include <Wt/WTextEdit>
#include <Wt/WTime>
#include <Wt/WTimer>
#include <Wt/WTimerWidget>
#include <Wt/WTransform>
#include <Wt/WTree>
#include <Wt/WTreeNode>
#include <Wt/WTreeTable>
#include <Wt/WTreeTableNode>
#include <Wt/WTreeView>
#include <Wt/WValidationStatus>
#include <Wt/WValidator>
#include <Wt/WVBoxLayout>
#include <Wt/WVectorImage>
#include <Wt/WVideo>
#include <Wt/WViewWidget>
#include <Wt/WVirtualImage>
#include <Wt/WVmlImage>
#include <Wt/WWebWidget>
#include <Wt/WWidget>
#include <Wt/WWidgetItem>
